name:                hagrad
version:             0.1.0.0
github:              "githubuser/hagrad"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hagrad#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hagrad-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hagrad

tests:
  hagrad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hagrad
    - hspec ^>=2.7
    - hspec-discover ^>=2.7

    - QuickCheck ^>= 2.14.2
    - hspec-core ^>= 2.7.9
    - hspec-expectations ^>= 0.8.2
    - HUnit ^>= 1.6.2.0
    - ansi-terminal ^>= 0.11.5
    - call-stack ^>= 0.4.0
    - clock ^>= 0.8.3
    - quickcheck-io ^>= 0.2.0
    - random ^>= 1.2.1.1
    - setenv ^>= 0.1.1.3
    - splitmix ^>= 0.1.0.4
    - tf-random ^>= 0.5
    - ansi-terminal-types ^>= 0.11.5
    - colour ^>= 2.3.6
    - primitive ^>= 0.8.0.0
    - data-array-byte ^>= 0.1.0.1
